# Generated by Django 5.1.2 on 2024-12-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('term', 'lesson_type', 'student', 'tutor')},
        ),
    ]
