# Generated by Django 5.1.2 on 2024-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='subjects',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('term', 'lesson_type', 'student', 'tutor')},
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(related_name='tutors', to='tutorials.subject'),
        ),
    ]
