# Generated by Django 5.1.2 on 2024-12-08 13:24

from django.db import migrations


def add_predefined_subjects(apps, schema_editor):
    # Get the model for 'Subject'
    Subject = apps.get_model('tutorials', 'Subject')

    # List of predefined subjects
    subjects = ['Python', 'Java', 'JavaScript', 'React', 'Ruby', 'Go', 'HTML/CSS', 'C', 'Scala']
    
    # Create or get the subjects (this avoids duplicates)
    for subject in subjects:
        Subject.objects.get_or_create(name=subject)

class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_subject_alter_tutor_rate_remove_tutor_subjects_and_more'),
    ]

    operations = [
        migrations.RunPython(add_predefined_subjects),
    ]
