# Generated by Django 5.1.2 on 2024-11-15 14:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='session',
            name='topic',
        ),
        migrations.AddField(
            model_name='session',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Format: [hours]:[minutes]'),
        ),
        migrations.AddField(
            model_name='session',
            name='lesson_type',
            field=models.CharField(choices=[('Fortnight', 'Fortnight'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly')], default='Weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='session_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.CharField(choices=[('Bush House', 'Bush House'), ('Waterloo Campus', 'Waterloo Campus')], default='Bush House', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
