# Generated by Django 4.2.16 on 2024-12-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_booking_unique_together'),
        ('tutorials', '0003_populate_subjects'),
    ]

    operations = [
    ]
