# Generated by Django 5.1.2 on 2024-11-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_student_email_alter_student_username'),
        ('tutorials', '0004_remove_session_notes_remove_session_topic_and_more'),
    ]

    operations = [
    ]
