# Generated by Django 5.1.2 on 2024-12-10 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_booking_student_alter_booking_tutor_and_more'),
        ('tutorials', '0004_merge_20241210_1358'),
    ]

    operations = [
    ]
