# Generated by Django 5.1.2 on 2024-12-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_populate_subjects'),
        ('tutorials', '0004_remove_session_notes_remove_session_topic_and_more'),
    ]

    operations = [
    ]
