# Generated by Django 5.1.2 on 2024-11-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutor'),
        ('tutorials', '0005_merge_20241125_2301'),
    ]

    operations = [
    ]
