# Generated by Django 4.2.16 on 2024-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_alter_student_username_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
