# Generated by Django 5.1.2 on 2024-11-26 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_merge_0002_tutor_0005_merge_20241125_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('term', 'student', 'tutor')},
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('booking', 'session_date', 'session_time'), name='unique_booking_session_datetime'),
        ),
    ]
