# Generated by Django 5.1.2 on 2024-11-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_alter_tutor_username_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Javascript', 'Javascript'), ('React', 'React'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('HTML/CSS', 'HTML/CSS'), ('C', 'C'), ('Scala', 'Scala')], default='Python', max_length=100),
        ),
    ]
