# Generated by Django 4.2.16 on 2024-11-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_alter_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful')], default='Pending', max_length=10),
        ),
    ]
