# Generated by Django 5.1.2 on 2024-11-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_alter_tutor_subject'),
        ('tutorials', '0009_student_payment'),
    ]

    operations = [
    ]
