# Generated by Django 5.1.2 on 2024-12-02 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_merge_0008_alter_tutor_subject_0009_student_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
    ]
