# Generated by Django 5.1.2 on 2024-12-01 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='amount',
        ),
        migrations.AddField(
            model_name='tutor',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
