# Generated by Django 4.2.16 on 2024-12-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('profile_update', 'Profile Update'), ('password_reset', 'Password Reset'), ('course_enrollment', 'Course Enrollment'), ('tutor_assignment', 'Tutor Assignment'), ('session_schedule', 'Session Scheduling'), ('payment_issue', 'Payment Issue'), ('technical_support', 'Technical Support'), ('feedback_complaint', 'Feedback/Complaint'), ('custom_request', 'Custom Request')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
