# Generated by Django 5.1.2 on 2024-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_remove_session_amount_tutor_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='lesson_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='lesson_type',
            field=models.CharField(choices=[('Fortnight', 'Fortnight'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly')], default='Weekly', max_length=10),
        ),
    ]
