# Generated by Django 5.1.2 on 2024-12-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_alter_tutor_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
