# Generated by Django 5.1.2 on 2024-12-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_remove_session_lesson_type_booking_lesson_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['term', 'lesson_type', 'student', 'tutor']},
        ),
        migrations.AddField(
            model_name='session',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('term', 'lesson_type', 'student', 'tutor')},
        ),
    ]
