# Generated by Django 5.1.2 on 2024-12-03 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_alter_booking_options_session_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
