# Generated by Django 5.1.2 on 2024-12-03 13:22

from django.db import migrations

def add_predefined_subjects(apps, schema_editor):
    Subject = apps.get_model('tutorials', 'Subject')
    subjects = ['Python', 'Java', 'Javascript', 'React', 'Ruby', 'Go', 'HTML/CSS', 'C', 'Scala']
    for name in subjects:
        Subject.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_subject_remove_tutor_subject_tutor_subjects'),
    ]

    operations = [
        migrations.RunPython(add_predefined_subjects),
    ]
