# Generated by Django 5.1.2 on 2024-12-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_alter_user_user_type'),
        ('tutorials', '0015_remove_session_total_amount_alter_tutor_rate'),
    ]

    operations = [
    ]
